/*
DeepL API

The DeepL API provides programmatic access to DeepL’s machine translation technology.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ListGlossaryLanguages200ResponseSupportedLanguagesInner struct for ListGlossaryLanguages200ResponseSupportedLanguagesInner
type ListGlossaryLanguages200ResponseSupportedLanguagesInner struct {
	// The language in which the source texts in the glossary are specified.
	SourceLang string `json:"source_lang"`
	// The language in which the target texts in the glossary are specified.
	TargetLang string `json:"target_lang"`
}

// NewListGlossaryLanguages200ResponseSupportedLanguagesInner instantiates a new ListGlossaryLanguages200ResponseSupportedLanguagesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListGlossaryLanguages200ResponseSupportedLanguagesInner(sourceLang string, targetLang string) *ListGlossaryLanguages200ResponseSupportedLanguagesInner {
	this := ListGlossaryLanguages200ResponseSupportedLanguagesInner{}
	this.SourceLang = sourceLang
	this.TargetLang = targetLang
	return &this
}

// NewListGlossaryLanguages200ResponseSupportedLanguagesInnerWithDefaults instantiates a new ListGlossaryLanguages200ResponseSupportedLanguagesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListGlossaryLanguages200ResponseSupportedLanguagesInnerWithDefaults() *ListGlossaryLanguages200ResponseSupportedLanguagesInner {
	this := ListGlossaryLanguages200ResponseSupportedLanguagesInner{}
	return &this
}

// GetSourceLang returns the SourceLang field value
func (o *ListGlossaryLanguages200ResponseSupportedLanguagesInner) GetSourceLang() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceLang
}

// GetSourceLangOk returns a tuple with the SourceLang field value
// and a boolean to check if the value has been set.
func (o *ListGlossaryLanguages200ResponseSupportedLanguagesInner) GetSourceLangOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceLang, true
}

// SetSourceLang sets field value
func (o *ListGlossaryLanguages200ResponseSupportedLanguagesInner) SetSourceLang(v string) {
	o.SourceLang = v
}

// GetTargetLang returns the TargetLang field value
func (o *ListGlossaryLanguages200ResponseSupportedLanguagesInner) GetTargetLang() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetLang
}

// GetTargetLangOk returns a tuple with the TargetLang field value
// and a boolean to check if the value has been set.
func (o *ListGlossaryLanguages200ResponseSupportedLanguagesInner) GetTargetLangOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetLang, true
}

// SetTargetLang sets field value
func (o *ListGlossaryLanguages200ResponseSupportedLanguagesInner) SetTargetLang(v string) {
	o.TargetLang = v
}

func (o ListGlossaryLanguages200ResponseSupportedLanguagesInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["source_lang"] = o.SourceLang
	}
	if true {
		toSerialize["target_lang"] = o.TargetLang
	}
	return json.Marshal(toSerialize)
}

type NullableListGlossaryLanguages200ResponseSupportedLanguagesInner struct {
	value *ListGlossaryLanguages200ResponseSupportedLanguagesInner
	isSet bool
}

func (v NullableListGlossaryLanguages200ResponseSupportedLanguagesInner) Get() *ListGlossaryLanguages200ResponseSupportedLanguagesInner {
	return v.value
}

func (v *NullableListGlossaryLanguages200ResponseSupportedLanguagesInner) Set(val *ListGlossaryLanguages200ResponseSupportedLanguagesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListGlossaryLanguages200ResponseSupportedLanguagesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListGlossaryLanguages200ResponseSupportedLanguagesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListGlossaryLanguages200ResponseSupportedLanguagesInner(val *ListGlossaryLanguages200ResponseSupportedLanguagesInner) *NullableListGlossaryLanguages200ResponseSupportedLanguagesInner {
	return &NullableListGlossaryLanguages200ResponseSupportedLanguagesInner{value: val, isSet: true}
}

func (v NullableListGlossaryLanguages200ResponseSupportedLanguagesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListGlossaryLanguages200ResponseSupportedLanguagesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


